name: Update Schedule

on:
  schedule:
    # Запуск кожну годину у 5-ту хвилину (напр. 10:05, 11:05)
    - cron: '5 * * * *'
  workflow_dispatch: # Дозволяє запускати вручну кнопкою на GitHub

jobs:
  run-parser:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go Parser
        run: go run main.go
        env:
          TZ: Europe/Kyiv

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add discos-5.1.ics
          git commit -m "Auto-update: $(date +'%d.%m.%Y %H:%M')" || echo "No changes to commit"
          git push